### ISSUE TITLE
cq function is missing

### ISSUE THREAD

**Issue by iagomosqueira** [SMBaylis/fishSim#9]
Following the code in the vignette, the call to `mate` fails as `cq()` is missing

```
library(fishSim)
indiv <- makeFounders(stocks = c(1))
indiv <- mate(indiv, year = 1)
Error in cq(Me, Sex, Dad, Mum) : could not find function "cq"
```

**Comment by SMBaylis** [comment]
Thanks - should be fixed now!

**Comment by iagomosqueira** [comment]
Thanks. Got a new error,

```
> indiv <- mate(indiv, year = 1)
Error in inds %is.a% "data.frame" : could not find function "%is.a%"
```

Is any package missing in NAMESPACE? Could not find in which package `%is.a%` is defined.

**Comment by SMBaylis** [comment]
Both `cq` and `%is.a%` are in mvbutils, and are being called by `dfify`. We've recently (ish) refactored some of the internals, and `dfify` is a convenience function that converts between versions on-the-fly. The old versions (and so the converter) shouldn't really be in the package any more. The current push has removed them, so there should be no more mvbutils in the main toolchain.

**Comment by iagomosqueira** [comment]
Great, working now. You need to delete mvbutils from [NAMESPACE](https://github.com/SMBaylis/fishSim/blob/master/fishSim/NAMESPACE#L32), or really from [here](https://github.com/SMBaylis/fishSim/blob/master/fishSim/R/fishSim_dev.R#L12).

**Comment by SMBaylis** [comment]
I think I'll keep it in - we've been experimenting with a (much) quicker version of `findRelativesPar()` (see `quickin()` ). It uses a couple of mvbutils funcs, so it's still a necessary import.

**Comment by iagomosqueira** [comment]
Perfect, thanks
